steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/trusty-bearing-366601/imdb-training', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/trusty-bearing-366601/imdb-training']
images:
- gcr.io/trusty-bearing-366601/imdb-training